### VALUES YOU SHOULD CHANGE ###

# 通用网站设置
# title: 这将作为网站名称显示在浏览器标签中
title: YuXiaoLong
# description: 这将是HTML元标签的内容，可以忽略.
description: 余小龙个人网站
# baseurl: 你网站的子路径
# > 如果你将仓库重命名为 <用户>.github.io，请将此设置为空字符串 ""
baseurl: ""

# 首页设置
# username: 这将作为你的名字显示在首页上.
username: 余
# typing_text: 这将在 '向下滚动查看更多' 之前显示.
# > 将其设置为你的职位，例如 全栈开发者
typing_text: design
# email: 用于电子邮件按钮的你的电子邮件地址.
email: 694837565@qq.com
# 对于你想要显示的每个社交按钮，设置你的用户名或用户ID
# 如果你不使用以下任何一个网站，则留空
# > twitter_username:
github_username: aaa
codepen_username: bbbb
dev_username: cccc
linkedin_username: dddd
twitter_username: eeee

# 关于我板块
# show_aboutme_card:
# > 将此设置为true，将显示关于我板块
# > 将此设置为false，将省略关于我板块
show_aboutme_card: true
# about_me_title: 这将作为关于我板块的标题显示
about_me_title: 关于我
# about_me_description: 这将显示在标题下方.
about_me_description: 一项测试，自我介绍.

# 技能板块
# show_skills_card:
# > 将此设置为true，将显示技能板块
# > 将此设置为false，将省略技能板块
show_skills_card: true
# about_me_title: 这将作为技能板块的标题显示
skills_title: 技能

# 时间线板块
# show_timeline_card:
# > 将此设置为true，将显示时间线板块
# > 将此设置为false，将省略时间线板块
show_timeline_card: true
# timeline_title:这将作为时间线板块的标题显示
timeline_title: 教育与经验
# cv_download_link: 你存放简历的链接
# >例如，你将简历分享在Dropbox上，那么在此添加Dropbox链接
cv_download_link: 无

# 项目板块
# show_projects_card:
# > 将此设置为true，将显示项目板块
# > 将此设置为false，将省略项目板块
show_projects_card: true
# show_projects:
# > 将此设置为true，将显示 _data/projects.yml 中列出的项目
# > 将此设置为false，将省略列出的项目
show_projects: true
# projects_title:这将作为你项目的标题显示
projects_title: 项目
# show_os_projects:
# > 将此设置为true，将显示你在GitHub上的公共项目
# > 将此设置为false，将省略你在GitHub上的公共项目
show_os_projects: true
# os_projects_title:这将作为你开源项目的标题显示
os_projects_title: 测试项目

# 联系板块
# show_contact_card:
# > 将此设置为true，将显示联系板块
# > 将此设置为false，将省略联系板块
show_contact_card: true
# contact_title: 这将作为联系板块的标题显示
contact_title: 联系我
# contact_description: 这将显示在标题下方
contact_description: 18801322355

# GitHub元数据
# 将此设置为你的fork仓库
# > 例如 <用户>/<用户>.github.io
repository: XL-Yu
projects:
  # sortby:
  # > 如果你想按时间对GitHub仓库进行排序，请将此设置为pushed
  # > 如果你想按星标数对GitHub仓库进行排序，请将此设置为stars
  sort_by: pushed
  exclude:
    # archived:
    # > 将此设置为true，将排除已存档的仓库
    # > 将此设置为false，也将显示已存档的仓库
    archived: true
    # forks:
    # > 将此设置为true，将排除fork的仓库
    # > 将此设置为false，也将显示fork的仓库
    forks: true
    # projects: 你想从列表中排除的仓库名称列表
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# 如果你想使用Google Analytics跟踪你的网站，请设置ID
# > 如果你不想使用Google Analytics进行跟踪，请将此设置为空字符串 ""
google-analytics:
  id: ""

### 结束你应该修改的值 ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
